name: Review

on: [pull_request]

jobs:
  build:

    runs-on: macOS-13

    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_15.0.app'
    - name: bundle install
      run: |
        bundle install
        bundle exec fastlane review
